# Site settings
title: Conscious Journeys - Explorations into Energy, Existence, and Enlightenment
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://abrahamnash.github.io/" # the base hostname & protocol for your site
twitter_username: username
github_username: abrahamnash

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
